// Banque de sujets : 3 langues × 3 paliers (A = A1-A2, B = B1-B2, C = C1-C2), taggés par centre d'intérêt.
window.DST_DATA = {
  LANGS: {
    fr: { label: 'FR', bcp: 'fr-FR', fillers: /\b(euh+|hum+|ben|bah)\b/gi },
    en: { label: 'EN', bcp: 'en-US', fillers: /\b(um+|uh+|erm+|like|you know)\b/gi },
    es: { label: 'ES', bcp: 'es-ES', fillers: /\b(eh+|em+|este|pues|o sea)\b/gi }
  },

  LEVELS: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
  DURATIONS: [1, 2, 3, 5],
  // Les libellés traduits sont dans i18n.js ; ces clés servent de tags pour les sujets.
  INTERESTS: ['Voyage', 'Cuisine', 'Cinéma', 'Sport', 'Écologie', 'Tech', 'Musique', 'Travail', 'Études'],
  OBJECTIVES: ['free', 'delf', 'ielts', 'toefl'],

  TOPICS: [
    // ------------------------------------------------------------------ FR · A
    { lang: 'fr', bucket: 'A', tags: ['Voyage'], text: 'Décris ta ville : où tu habites, ce que tu aimes et ce que tu n\'aimes pas.',
      hints: ['Le quartier : calme ou animé ?', 'Un endroit que tu aimes, et pourquoi.', 'Une chose que tu voudrais changer.'],
      vocab: [['un quartier', 'une partie de la ville'], ['animé', 'avec beaucoup de monde et de bruit'], ['un commerce', 'un magasin'], ['les transports', 'bus, métro, taxi…'], ['déménager', 'changer de logement']],
      followup: 'Si tu pouvais habiter n\'importe où, tu choisirais quelle ville ?' },
    { lang: 'fr', bucket: 'A', tags: ['Cuisine'], text: 'Qu\'est-ce que tu manges le matin ? Raconte ton petit-déjeuner idéal.',
      hints: ['Ce que tu bois, ce que tu manges.', 'Seul ou avec quelqu\'un ?', 'Le week-end, c\'est différent ?'],
      vocab: [['le petit-déjeuner', 'le repas du matin'], ['une tartine', 'du pain avec du beurre ou de la confiture'], ['sucré / salé', 'les deux goûts principaux'], ['prendre son temps', 'ne pas se presser'], ['avoir faim', 'vouloir manger']],
      followup: 'Et le repas du soir, tu le prépares toi-même ?' },
    { lang: 'fr', bucket: 'A', tags: ['Sport', 'Musique'], text: 'Qu\'est-ce que tu fais le week-end pour te détendre ?',
      hints: ['Une activité dehors, une activité dedans.', 'Avec qui ?', 'À quelle heure tu te lèves ?'],
      vocab: [['se détendre', 'se reposer, relâcher'], ['une balade', 'une promenade'], ['faire la grasse matinée', 'dormir tard le matin'], ['un loisir', 'une activité pour le plaisir'], ['rejoindre', 'aller retrouver quelqu\'un']],
      followup: 'Quel est ton meilleur souvenir de week-end ?' },
    { lang: 'fr', bucket: 'A', tags: ['Études', 'Travail'], text: 'Présente-toi : ce que tu étudies ou ton travail, et pourquoi tu as choisi ça.',
      hints: ['Ton nom, ton âge, ta ville.', 'Ce que tu fais chaque jour.', 'Ce que tu veux faire plus tard.'],
      vocab: [['une formation', 'des études pour un métier'], ['un stage', 'travail court pour apprendre'], ['un métier', 'une profession'], ['choisir', 'décider entre plusieurs choses'], ['plus tard', 'dans le futur']],
      followup: 'Qu\'est-ce qui est le plus difficile dans tes études ou ton travail ?' },
    { lang: 'fr', bucket: 'A', tags: ['Sport'], text: 'Tu fais du sport ? Raconte-moi une activité physique que tu pratiques ou que tu aimerais essayer.',
      hints: ['À quelle fréquence, et depuis quand.', 'Comment tu te sens après.', 'Ce qui te motive à continuer.'],
      vocab: [['s\'entraîner', 'faire du sport régulièrement'], ['transpirer', 'suer pendant l\'effort'], ['une séance', 'un moment d\'entraînement'], ['se motiver', 'trouver l\'envie de faire quelque chose'], ['un adversaire', 'la personne contre qui on joue']],
      followup: 'Tu préfères t\'entraîner seul ou en groupe ?' },
    { lang: 'fr', bucket: 'A', tags: ['Tech'], text: 'Quel est l\'appareil ou l\'application que tu utilises le plus chaque jour ?',
      hints: ['Lequel, et depuis quand.', 'Ce que tu ferais sans.', 'Un moment où tu l\'as utilisé aujourd\'hui.'],
      vocab: [['une application', 'un programme sur téléphone'], ['un écran', 'la surface qui affiche l\'image'], ['télécharger', 'installer sur son appareil'], ['une notification', 'un message qui s\'affiche'], ['se déconnecter', 'arrêter d\'utiliser un appareil']],
      followup: 'Tu as déjà essayé de t\'en passer un jour entier ?' },

    // ------------------------------------------------------------------ FR · B
    { lang: 'fr', bucket: 'B', tags: ['Voyage'], text: 'Raconte-moi un voyage qui ne s\'est pas passé comme prévu, et ce que tu en as retenu.',
      hints: ['Le moment précis où ça a dérapé, décris la scène, pas le résumé.', 'Ce que tu as ressenti sur le coup, et ce que tu en penses aujourd\'hui.', 'Ce que tu ferais différemment, au conditionnel, c\'est l\'exercice.'],
      vocab: [['un imprévu', 'ce qui arrive sans qu\'on l\'ait prévu'], ['rater / louper', 'ne pas réussir à prendre (un train, un avion)'], ['le décalage horaire', 'la différence d\'heure entre deux pays'], ['une escale', 'un arrêt pendant un trajet'], ['se débrouiller', 'trouver une solution seul']],
      followup: 'Tu as parlé de ce voyage, qu\'est-ce qui t\'a le plus surpris là-bas ?' },
    { lang: 'fr', bucket: 'B', tags: ['Écologie'], text: 'Est-ce que tu as changé une habitude pour l\'environnement ? Laquelle, et est-ce que ça a tenu ?',
      hints: ['L\'habitude d\'avant, et le déclic.', 'Ce qui a été facile, ce qui a été dur.', 'Est-ce que ton entourage a suivi ?'],
      vocab: [['un geste', 'une petite action'], ['le gaspillage', 'utiliser trop, jeter inutilement'], ['tenir bon', 'continuer malgré la difficulté'], ['à long terme', 'sur une longue durée'], ['culpabiliser', 'se sentir coupable']],
      followup: 'À ton avis, c\'est aux individus ou aux États de faire l\'effort ?' },
    { lang: 'fr', bucket: 'B', tags: ['Cinéma', 'Musique'], text: 'Parle-moi d\'un film ou d\'un album qui t\'a marqué. Pourquoi celui-là ?',
      hints: ['Le contexte : quand, avec qui, dans quel état d\'esprit.', 'Une scène ou un morceau précis.', 'Ce que ça a changé pour toi.'],
      vocab: [['marquer', 'laisser une trace durable'], ['une bande-son', 'la musique d\'un film'], ['bouleversant', 'qui provoque une forte émotion'], ['un navet', 'un très mauvais film'], ['revoir en boucle', 'regarder encore et encore']],
      followup: 'Tu le recommanderais à qui, et avec quel avertissement ?' },
    { lang: 'fr', bucket: 'B', tags: ['Travail', 'Tech'], text: 'Le télétravail : un progrès ou un piège ? Défends ta position.',
      hints: ['Ton expérience, ou celle d\'un proche.', 'Un avantage concret, un inconvénient concret.', 'Nuance : pour quels métiers ?'],
      vocab: [['la frontière vie pro / vie perso', 'la limite entre travail et vie privée'], ['un piège', 'quelque chose qui semble bien mais nuit'], ['être joignable', 'pouvoir être contacté'], ['l\'isolement', 'le fait d\'être seul'], ['un compromis', 'un accord au milieu']],
      followup: 'Si ton employeur imposait cinq jours au bureau, tu réagirais comment ?' },
    { lang: 'fr', bucket: 'B', tags: ['Études', 'Tech'], text: 'Raconte un moment où tu as dû apprendre quelque chose très vite. Comment tu t\'y es pris ?',
      hints: ['La situation et la pression.', 'Ta méthode, étape par étape.', 'Ce que tu garderais de cette méthode.'],
      vocab: [['s\'y prendre', 'procéder, agir d\'une certaine manière'], ['être sous pression', 'avoir peu de temps, du stress'], ['bachoter', 'apprendre vite pour un examen'], ['assimiler', 'comprendre et retenir'], ['une échéance', 'une date limite']],
      followup: 'Et qu\'est-ce que tu as oublié le plus vite ensuite ?' },
    { lang: 'fr', bucket: 'B', tags: ['Travail', 'Études'], text: 'Raconte-moi ton premier jour dans un travail ou un stage. Qu\'est-ce qui t\'a marqué ?',
      hints: ['Le stress du début, décris ce que tu ressentais.', 'Une rencontre ou un moment précis de cette journée.', 'Un moment gênant, si tu en as un.'],
      vocab: [['un entretien', 'une rencontre pour évaluer un candidat'], ['s\'intégrer', 'trouver sa place dans un groupe'], ['une collègue', 'une personne avec qui on travaille'], ['maladroit', 'gauche, pas naturel'], ['prendre ses marques', 's\'habituer à un nouvel endroit']],
      followup: 'Et aujourd\'hui, qu\'est-ce que tu dirais à la version de toi ce jour-là ?' },
    { lang: 'fr', bucket: 'B', tags: ['Musique', 'Cinéma'], text: 'Raconte-moi un concert ou un spectacle qui t\'a marqué, en bien ou en mal.',
      hints: ['L\'ambiance avant que ça commence.', 'Un moment précis sur scène.', 'Ce que tu as ressenti en repartant.'],
      vocab: [['une ambiance', 'l\'atmosphère d\'un lieu'], ['un rappel', 'un retour de l\'artiste après la fin'], ['être déçu', 'ne pas avoir ce qu\'on attendait'], ['bondé', 'plein de monde'], ['l\'attente', 'le temps avant que ça commence']],
      followup: 'Tu irais revoir le même artiste ?' },

    // ------------------------------------------------------------------ FR · C
    { lang: 'fr', bucket: 'C', tags: ['Tech', 'Travail'], text: 'L\'intelligence artificielle va-t-elle rendre certaines compétences humaines obsolètes, ou au contraire plus précieuses ?',
      hints: ['Choisis une compétence précise et tiens-la jusqu\'au bout.', 'Concède un point à la thèse adverse avant de la réfuter.', 'Termine par une conséquence pour toi, personnellement.'],
      vocab: [['obsolète', 'dépassé, qui ne sert plus'], ['une plus-value', 'une valeur ajoutée'], ['déléguer', 'confier à quelqu\'un ou quelque chose'], ['en revanche', 'par contre'], ['le discernement', 'la capacité à juger avec justesse']],
      followup: 'Quelle compétence tu refuserais absolument de déléguer à une machine ?' },
    { lang: 'fr', bucket: 'C', tags: ['Écologie', 'Voyage'], text: 'Faut-il renoncer à l\'avion pour voyager de manière responsable ? Nuance ta réponse.',
      hints: ['Distingue les usages : loisir, famille, travail.', 'Cite une alternative concrète et ses limites.', 'Qui doit porter la responsabilité ?'],
      vocab: [['renoncer à', 'abandonner volontairement'], ['une empreinte', 'l\'impact laissé'], ['pour autant', 'malgré cela'], ['un arbitrage', 'un choix entre priorités'], ['la sobriété', 'consommer moins, volontairement']],
      followup: 'Tu as évoqué des alternatives, laquelle tu as réellement testée ?' },
    { lang: 'fr', bucket: 'C', tags: ['Cinéma', 'Musique'], text: 'Une œuvre peut-elle être séparée de son auteur ? Prends un exemple qui te dérange vraiment.',
      hints: ['Décris le malaise, pas seulement les faits.', 'Différencie écouter en privé et promouvoir en public.', 'Est-ce que ta position a évolué ?'],
      vocab: [['dissocier', 'séparer deux choses liées'], ['un malaise', 'une gêne diffuse'], ['cautionner', 'approuver, soutenir'], ['l\'héritage', 'ce qui reste après quelqu\'un'], ['trancher', 'décider nettement']],
      followup: 'Et si l\'auteur en question était un proche, ta réponse serait la même ?' },
    { lang: 'fr', bucket: 'C', tags: ['Travail', 'Tech'], text: 'Le mérite individuel existe-t-il vraiment, ou la réussite dépend-elle surtout du contexte ?',
      hints: ['Distingue effort personnel et circonstances de départ.', 'Cite un exemple concret pour appuyer ta position.', 'Nuance ta position en concédant un point.'],
      vocab: [['le mérite', 'la valeur reconnue à un effort'], ['un déterminisme', 'l\'idée que le contexte détermine le résultat'], ['relativiser', 'remettre en perspective, nuancer'], ['un privilège', 'un avantage non mérité par l\'effort'], ['une trajectoire', 'le parcours d\'une vie']],
      followup: 'Et ta propre réussite, tu la mets sur quel compte ?' },

    // ------------------------------------------------------------------ EN · A
    { lang: 'en', bucket: 'A', tags: ['Voyage'], text: 'Describe your city: where you live, what you like, and what you don\'t like.',
      hints: ['Your neighbourhood: quiet or busy?', 'One place you love, and why.', 'One thing you would change.'],
      vocab: [['a neighbourhood', 'a part of a city'], ['busy', 'with lots of people and noise'], ['a shop', 'a place where you buy things'], ['public transport', 'buses, trains, taxis'], ['to move house', 'to change where you live']],
      followup: 'If you could live anywhere, which city would you choose?' },
    { lang: 'en', bucket: 'A', tags: ['Cuisine'], text: 'What do you eat in the morning? Tell me about your ideal breakfast.',
      hints: ['What you drink, what you eat.', 'Alone or with someone?', 'Is the weekend different?'],
      vocab: [['breakfast', 'the morning meal'], ['toast', 'grilled bread'], ['sweet / savoury', 'the two main tastes'], ['to take your time', 'not to hurry'], ['to be hungry', 'to want food']],
      followup: 'And dinner, do you cook it yourself?' },
    { lang: 'en', bucket: 'A', tags: ['Sport', 'Musique'], text: 'What do you do at the weekend to relax?',
      hints: ['One activity outside, one inside.', 'With whom?', 'What time do you get up?'],
      vocab: [['to relax', 'to rest'], ['a walk', 'going on foot for pleasure'], ['to sleep in', 'to stay in bed late'], ['a hobby', 'an activity for fun'], ['to meet up', 'to see friends']],
      followup: 'What is your best weekend memory?' },
    { lang: 'en', bucket: 'A', tags: ['Études', 'Travail'], text: 'Introduce yourself: what you study or your job, and why you chose it.',
      hints: ['Your name, your age, your city.', 'What you do every day.', 'What you want to do later.'],
      vocab: [['a degree', 'a university qualification'], ['an internship', 'short work to learn a job'], ['a job', 'paid work'], ['to choose', 'to decide between options'], ['in the future', 'later in life']],
      followup: 'What is the hardest part of your studies or your job?' },
    { lang: 'en', bucket: 'A', tags: ['Sport'], text: 'Do you play sports? Tell me about one you practise or would like to try.',
      hints: ['How often, and since when.', 'How you feel afterwards.', 'What motivates you to keep going.'],
      vocab: [['to train', 'to practise sport regularly'], ['to sweat', 'to perspire during effort'], ['a session', 'one period of training'], ['to motivate yourself', 'to find the drive to do something'], ['an opponent', 'the person you play against']],
      followup: 'Do you prefer training alone or with others?' },
    { lang: 'en', bucket: 'A', tags: ['Tech'], text: 'What device or app do you use the most every day?',
      hints: ['Which one, and since when.', 'What you would do without it.', 'A moment you used it today.'],
      vocab: [['an app', 'a program on a phone'], ['a screen', 'the surface that shows the image'], ['to download', 'to install on your device'], ['a notification', 'a message that pops up'], ['to unplug', 'to stop using a device for a while']],
      followup: 'Have you ever tried going a whole day without it?' },

    // ------------------------------------------------------------------ EN · B
    { lang: 'en', bucket: 'B', tags: ['Voyage'], text: 'Tell me about a trip that went completely off the rails, and what you learned from it.',
      hints: ['The exact moment it went wrong: describe the scene, not the summary.', 'How you felt then, and how you see it now.', 'What you would do differently, use the conditional.'],
      vocab: [['a setback', 'a problem that stops progress'], ['to miss (a flight)', 'to arrive too late for it'], ['jet lag', 'tiredness after changing time zones'], ['a layover', 'a stop between two flights'], ['to make do', 'to manage with what you have']],
      followup: 'You mentioned that trip, what surprised you most once you were there?' },
    { lang: 'en', bucket: 'B', tags: ['Écologie'], text: 'Have you changed a habit for the environment? Which one, and did it last?',
      hints: ['The old habit, and the trigger.', 'What was easy, what was hard.', 'Did people around you follow?'],
      vocab: [['a small step', 'a minor action'], ['waste', 'using too much, throwing away'], ['to stick with it', 'to keep going'], ['in the long run', 'over a long time'], ['to feel guilty', 'to feel you did wrong']],
      followup: 'Is it up to individuals or governments to make the effort?' },
    { lang: 'en', bucket: 'B', tags: ['Cinéma', 'Musique'], text: 'Tell me about a film or an album that really stayed with you. Why that one?',
      hints: ['The context: when, with whom, in what mood.', 'One specific scene or track.', 'What it changed for you.'],
      vocab: [['to stay with someone', 'to leave a lasting impression'], ['a soundtrack', 'the music of a film'], ['overwhelming', 'causing very strong emotion'], ['a flop', 'a very bad film'], ['on repeat', 'again and again']],
      followup: 'Who would you recommend it to, and with what warning?' },
    { lang: 'en', bucket: 'B', tags: ['Travail', 'Tech'], text: 'Working from home: progress or a trap? Defend your position.',
      hints: ['Your experience, or someone close to you.', 'One concrete advantage, one concrete drawback.', 'Nuance: for which jobs?'],
      vocab: [['work-life balance', 'the line between work and private life'], ['a trap', 'something that looks good but harms you'], ['to be reachable', 'to be available for contact'], ['isolation', 'being alone'], ['a trade-off', 'accepting a loss for a gain']],
      followup: 'If your employer required five days in the office, how would you react?' },
    { lang: 'en', bucket: 'B', tags: ['Études', 'Tech'], text: 'Tell me about a time you had to learn something very fast. How did you go about it?',
      hints: ['The situation and the pressure.', 'Your method, step by step.', 'What you would keep from that method.'],
      vocab: [['to go about something', 'to approach a task'], ['under pressure', 'with little time, stressed'], ['to cram', 'to study intensely before an exam'], ['to take in', 'to understand and remember'], ['a deadline', 'a time limit']],
      followup: 'And what did you forget the fastest afterwards?' },
    { lang: 'en', bucket: 'B', tags: ['Travail', 'Études'], text: 'Tell me about your first day at a job or internship. What stood out?',
      hints: ['The nerves at the start, describe what you felt.', 'A specific encounter or moment from that day.', 'An awkward moment, if you have one.'],
      vocab: [['an interview', 'a meeting to assess a candidate'], ['to fit in', 'to find your place in a group'], ['a colleague', 'someone you work with'], ['awkward', 'not natural, clumsy'], ['to find your footing', 'to get used to a new place']],
      followup: 'What would you tell yourself on that day now?' },
    { lang: 'en', bucket: 'B', tags: ['Musique', 'Cinéma'], text: 'Tell me about a concert or show that stayed with you, good or bad.',
      hints: ['The mood before it started.', 'One specific moment on stage.', 'How you felt on the way home.'],
      vocab: [['an atmosphere', 'the mood of a place'], ['an encore', 'the artist coming back after the end'], ['to be disappointed', 'not to get what you expected'], ['packed', 'full of people'], ['the wait', 'the time before it starts']],
      followup: 'Would you go see the same artist again?' },

    // ------------------------------------------------------------------ EN · C
    { lang: 'en', bucket: 'C', tags: ['Tech', 'Travail'], text: 'Will artificial intelligence make some human skills obsolete, or more valuable than ever?',
      hints: ['Pick one specific skill and hold it to the end.', 'Concede a point to the opposing view before refuting it.', 'End with a consequence for you personally.'],
      vocab: [['obsolete', 'no longer useful'], ['added value', 'extra worth'], ['to delegate', 'to hand over to someone or something'], ['on the other hand', 'however'], ['judgement', 'the ability to decide wisely']],
      followup: 'Which skill would you absolutely refuse to hand over to a machine?' },
    { lang: 'en', bucket: 'C', tags: ['Écologie', 'Voyage'], text: 'Should we give up flying to travel responsibly? Give a nuanced answer.',
      hints: ['Separate the uses: leisure, family, work.', 'Name one concrete alternative and its limits.', 'Who should carry the responsibility?'],
      vocab: [['to give up', 'to stop voluntarily'], ['a footprint', 'the impact you leave'], ['nonetheless', 'despite that'], ['a trade-off', 'a choice between priorities'], ['restraint', 'choosing to consume less']],
      followup: 'You mentioned alternatives, which one have you actually tried?' },
    { lang: 'en', bucket: 'C', tags: ['Cinéma', 'Musique'], text: 'Can a work be separated from its author? Take an example that genuinely bothers you.',
      hints: ['Describe the discomfort, not just the facts.', 'Distinguish private listening from public endorsement.', 'Has your position changed over time?'],
      vocab: [['to separate', 'to keep apart'], ['unease', 'a vague discomfort'], ['to endorse', 'to publicly support'], ['legacy', 'what remains after someone'], ['to settle (a question)', 'to decide it firmly']],
      followup: 'If the author were someone close to you, would your answer be the same?' },
    { lang: 'en', bucket: 'C', tags: ['Travail', 'Tech'], text: 'Does individual merit really exist, or does success mostly depend on context?',
      hints: ['Separate personal effort from starting circumstances.', 'Give a concrete example to support your view.', 'Nuance your position by conceding a point.'],
      vocab: [['merit', 'the value given to an effort'], ['determinism', 'the idea that context shapes outcomes'], ['to put into perspective', 'to nuance, to relativise'], ['a privilege', 'an advantage not earned through effort'], ['a trajectory', 'the path of a life']],
      followup: 'And your own success, what do you put it down to?' },

    // ------------------------------------------------------------------ ES · A
    { lang: 'es', bucket: 'A', tags: ['Voyage'], text: 'Describe tu ciudad: dónde vives, qué te gusta y qué no te gusta.',
      hints: ['Tu barrio: ¿tranquilo o animado?', 'Un lugar que te gusta, y por qué.', 'Una cosa que cambiarías.'],
      vocab: [['un barrio', 'una parte de la ciudad'], ['animado', 'con mucha gente y ruido'], ['una tienda', 'un lugar para comprar'], ['el transporte público', 'autobús, metro, taxi'], ['mudarse', 'cambiar de casa']],
      followup: 'Si pudieras vivir en cualquier lugar, ¿qué ciudad elegirías?' },
    { lang: 'es', bucket: 'A', tags: ['Cuisine'], text: '¿Qué desayunas por la mañana? Cuéntame tu desayuno ideal.',
      hints: ['Qué bebes, qué comes.', '¿Solo o acompañado?', '¿El fin de semana es diferente?'],
      vocab: [['el desayuno', 'la comida de la mañana'], ['una tostada', 'pan tostado'], ['dulce / salado', 'los dos sabores principales'], ['tomarse su tiempo', 'no tener prisa'], ['tener hambre', 'querer comer']],
      followup: '¿Y la cena, la preparas tú?' },
    { lang: 'es', bucket: 'A', tags: ['Sport', 'Musique'], text: '¿Qué haces el fin de semana para relajarte?',
      hints: ['Una actividad fuera, una dentro.', '¿Con quién?', '¿A qué hora te levantas?'],
      vocab: [['relajarse', 'descansar'], ['un paseo', 'caminar por placer'], ['quedarse en la cama', 'dormir hasta tarde'], ['una afición', 'una actividad por gusto'], ['quedar con', 'reunirse con alguien']],
      followup: '¿Cuál es tu mejor recuerdo de un fin de semana?' },
    { lang: 'es', bucket: 'A', tags: ['Études', 'Travail'], text: 'Preséntate: qué estudias o cuál es tu trabajo, y por qué lo elegiste.',
      hints: ['Tu nombre, tu edad, tu ciudad.', 'Lo que haces cada día.', 'Lo que quieres hacer más adelante.'],
      vocab: [['una carrera', 'estudios universitarios'], ['unas prácticas', 'trabajo corto para aprender'], ['un oficio', 'una profesión'], ['elegir', 'decidir entre varias opciones'], ['más adelante', 'en el futuro']],
      followup: '¿Qué es lo más difícil de tus estudios o tu trabajo?' },
    { lang: 'es', bucket: 'A', tags: ['Sport'], text: '¿Practicas algún deporte? Cuéntame uno que practiques o te gustaría probar.',
      hints: ['Con qué frecuencia, y desde cuándo.', 'Cómo te sientes después.', 'Qué te motiva a seguir.'],
      vocab: [['entrenar', 'practicar deporte con regularidad'], ['sudar', 'transpirar durante el esfuerzo'], ['una sesión', 'un momento de entrenamiento'], ['motivarse', 'encontrar las ganas de hacer algo'], ['un rival', 'la persona contra la que juegas']],
      followup: '¿Prefieres entrenar solo o en grupo?' },

    // ------------------------------------------------------------------ ES · B
    { lang: 'es', bucket: 'B', tags: ['Voyage'], text: 'Cuéntame un viaje que no salió como esperabas, y qué aprendiste de él.',
      hints: ['El momento exacto en que se torció: describe la escena, no el resumen.', 'Lo que sentiste entonces, y lo que piensas hoy.', 'Lo que harías diferente, en condicional, ese es el ejercicio.'],
      vocab: [['un imprevisto', 'algo que ocurre sin planearlo'], ['perder (un vuelo)', 'llegar tarde y no tomarlo'], ['el jet lag', 'el cansancio por el cambio de hora'], ['una escala', 'una parada durante el trayecto'], ['apañárselas', 'encontrar una solución uno mismo']],
      followup: 'Hablaste de ese viaje, ¿qué fue lo que más te sorprendió allí?' },
    { lang: 'es', bucket: 'B', tags: ['Écologie'], text: '¿Has cambiado alguna costumbre por el medio ambiente? ¿Cuál, y ha durado?',
      hints: ['La costumbre anterior, y el detonante.', 'Lo que fue fácil, lo que fue difícil.', '¿La gente a tu alrededor te siguió?'],
      vocab: [['un gesto', 'una pequeña acción'], ['el despilfarro', 'usar demasiado, tirar sin necesidad'], ['aguantar', 'seguir a pesar de la dificultad'], ['a largo plazo', 'durante mucho tiempo'], ['sentirse culpable', 'pensar que hiciste algo mal']],
      followup: 'En tu opinión, ¿el esfuerzo lo deben hacer las personas o los gobiernos?' },
    { lang: 'es', bucket: 'B', tags: ['Cinéma', 'Musique'], text: 'Háblame de una película o un disco que te marcó. ¿Por qué ese?',
      hints: ['El contexto: cuándo, con quién, en qué estado de ánimo.', 'Una escena o una canción concreta.', 'Lo que cambió para ti.'],
      vocab: [['marcar', 'dejar una huella duradera'], ['la banda sonora', 'la música de una película'], ['conmovedor', 'que provoca una emoción fuerte'], ['un bodrio', 'una película muy mala'], ['en bucle', 'una y otra vez']],
      followup: '¿A quién se lo recomendarías, y con qué advertencia?' },
    { lang: 'es', bucket: 'B', tags: ['Travail', 'Tech'], text: 'El teletrabajo: ¿un avance o una trampa? Defiende tu postura.',
      hints: ['Tu experiencia, o la de alguien cercano.', 'Una ventaja concreta, un inconveniente concreto.', 'Matiza: ¿para qué trabajos?'],
      vocab: [['la conciliación', 'el equilibrio entre trabajo y vida privada'], ['una trampa', 'algo que parece bueno pero perjudica'], ['estar localizable', 'poder ser contactado'], ['el aislamiento', 'estar solo'], ['un término medio', 'un acuerdo intermedio']],
      followup: 'Si tu empresa exigiera cinco días en la oficina, ¿cómo reaccionarías?' },
    { lang: 'es', bucket: 'B', tags: ['Études', 'Tech'], text: 'Cuéntame una vez que tuviste que aprender algo muy rápido. ¿Cómo lo hiciste?',
      hints: ['La situación y la presión.', 'Tu método, paso a paso.', 'Lo que conservarías de ese método.'],
      vocab: [['arreglárselas', 'proceder de cierta manera'], ['estar bajo presión', 'tener poco tiempo, estrés'], ['empollar', 'estudiar intensamente antes de un examen'], ['asimilar', 'entender y retener'], ['un plazo', 'una fecha límite']],
      followup: '¿Y qué fue lo que olvidaste más rápido después?' },
    { lang: 'es', bucket: 'B', tags: ['Travail', 'Études'], text: 'Cuéntame tu primer día en un trabajo o unas prácticas. ¿Qué te marcó?',
      hints: ['Los nervios del principio, describe lo que sentías.', 'Un encuentro o momento concreto de ese día.', 'Un momento incómodo, si lo tuviste.'],
      vocab: [['una entrevista', 'una reunión para evaluar a un candidato'], ['integrarse', 'encontrar tu lugar en un grupo'], ['una compañera', 'una persona con quien trabajas'], ['torpe', 'poco natural, con poca soltura'], ['agarrar el ritmo', 'acostumbrarse a un lugar nuevo']],
      followup: '¿Qué le dirías hoy a esa versión de ti ese día?' },
    { lang: 'es', bucket: 'B', tags: ['Musique', 'Cinéma'], text: 'Cuéntame un concierto o espectáculo que te marcó, para bien o para mal.',
      hints: ['El ambiente antes de que empezara.', 'Un momento concreto en el escenario.', 'Cómo te sentiste al volver a casa.'],
      vocab: [['el ambiente', 'la atmósfera de un lugar'], ['un bis', 'el regreso del artista tras el final'], ['decepcionarse', 'no obtener lo que esperabas'], ['abarrotado', 'lleno de gente'], ['la espera', 'el tiempo antes de que empiece']],
      followup: '¿Volverías a ver al mismo artista?' },

    // ------------------------------------------------------------------ ES · C
    { lang: 'es', bucket: 'C', tags: ['Tech', 'Travail'], text: '¿La inteligencia artificial hará obsoletas algunas competencias humanas, o más valiosas que nunca?',
      hints: ['Elige una competencia concreta y mantenla hasta el final.', 'Concede un punto a la tesis contraria antes de refutarla.', 'Termina con una consecuencia para ti, personalmente.'],
      vocab: [['obsoleto', 'anticuado, que ya no sirve'], ['un valor añadido', 'un plus'], ['delegar', 'confiar a alguien o algo'], ['en cambio', 'por el contrario'], ['el criterio', 'la capacidad de juzgar con acierto']],
      followup: '¿Qué competencia te negarías rotundamente a delegar en una máquina?' },
    { lang: 'es', bucket: 'C', tags: ['Écologie', 'Voyage'], text: '¿Hay que renunciar al avión para viajar de forma responsable? Matiza tu respuesta.',
      hints: ['Distingue los usos: ocio, familia, trabajo.', 'Cita una alternativa concreta y sus límites.', '¿Quién debe asumir la responsabilidad?'],
      vocab: [['renunciar a', 'abandonar voluntariamente'], ['la huella', 'el impacto que dejamos'], ['aun así', 'a pesar de eso'], ['una disyuntiva', 'una elección entre prioridades'], ['la sobriedad', 'consumir menos por decisión propia']],
      followup: 'Mencionaste alternativas, ¿cuál has probado de verdad?' },
    { lang: 'es', bucket: 'C', tags: ['Cinéma', 'Musique'], text: '¿Se puede separar una obra de su autor? Pon un ejemplo que te incomode de verdad.',
      hints: ['Describe la incomodidad, no solo los hechos.', 'Diferencia escuchar en privado y promover en público.', '¿Ha evolucionado tu postura?'],
      vocab: [['disociar', 'separar dos cosas unidas'], ['un malestar', 'una incomodidad difusa'], ['avalar', 'aprobar, apoyar'], ['el legado', 'lo que queda tras alguien'], ['zanjar', 'decidir de forma tajante']],
      followup: 'Y si el autor fuera alguien cercano, ¿tu respuesta sería la misma?' },
    { lang: 'es', bucket: 'C', tags: ['Travail', 'Tech'], text: '¿Existe realmente el mérito individual, o el éxito depende sobre todo del contexto?',
      hints: ['Distingue el esfuerzo personal de las circunstancias de partida.', 'Cita un ejemplo concreto para apoyar tu postura.', 'Matiza tu posición concediendo un punto.'],
      vocab: [['el mérito', 'el valor reconocido a un esfuerzo'], ['un determinismo', 'la idea de que el contexto determina el resultado'], ['relativizar', 'poner en perspectiva, matizar'], ['un privilegio', 'una ventaja no ganada con esfuerzo'], ['una trayectoria', 'el recorrido de una vida']],
      followup: '¿Y tu propio éxito, a qué lo atribuyes?' }
  ]
};
